In [297]:
import pandas as pd
import matplotlib as plt

In [298]:
df = pd.read_csv('train.csv')
test =pd.read_csv('test.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [299]:
nan_col = [i for i in df.columns if df[i].isnull().any()]
for i in nan_col:
    print(i, df[i].isnull().sum())

LotFrontage 259
Alley 1369
MasVnrType 8
MasVnrArea 8
BsmtQual 37
BsmtCond 37
BsmtExposure 38
BsmtFinType1 37
BsmtFinType2 38
Electrical 1
FireplaceQu 690
GarageType 81
GarageYrBlt 81
GarageFinish 81
GarageQual 81
GarageCond 81
PoolQC 1453
Fence 1179
MiscFeature 1406

In [300]:
dropped_cols = ['Alley', 'PoolQC', 'Fence', 'MiscFeature', 'FireplaceQu']
df = df.drop(dropped_cols, axis = 1)
test = test.drop(dropped_cols, axis = 1)

In [301]:
df = df.apply(lambda x: x.fillna(x.value_counts().index[0]))
test = test.apply(lambda x: x.fillna(x.value_counts().index[0]))

In [302]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [303]:
df = pd.get_dummies(df).astype(int)
test = pd.get_dummies(test).astype(int)

In [304]:
com_col = (df.columns).intersection(test.columns)
dif_col = (df.columns).difference(test.columns)

In [305]:
test.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80,11622,5,6,1961,1961,0,468,...,0,0,0,1,0,0,0,0,1,0
1,1462,20,81,14267,6,6,1958,1958,108,923,...,0,0,0,1,0,0,0,0,1,0
2,1463,60,74,13830,5,5,1997,1998,0,791,...,0,0,0,1,0,0,0,0,1,0
3,1464,60,78,9978,6,6,1998,1998,20,602,...,0,0,0,1,0,0,0,0,1,0
4,1465,120,43,5005,8,5,1992,1992,0,263,...,0,0,0,1,0,0,0,0,1,0

In [306]:
print(dif_col)

Index(['Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn',
       'Electrical_Mix', 'Exterior1st_ImStucc', 'Exterior1st_Stone',
       'Exterior2nd_Other', 'GarageQual_Ex', 'Heating_Floor', 'Heating_OthW',
       'HouseStyle_2.5Fin', 'RoofMatl_ClyTile', 'RoofMatl_Membran',
       'RoofMatl_Metal', 'RoofMatl_Roll', 'SalePrice', 'Utilities_NoSeWa'],
      dtype='object')

In [307]:
for i in dif_col:
    test.insert(251,i,0)
test = test.drop('SalePrice',axis=1)

In [308]:
test = test.reindex(sorted(test.columns),axis=1)

In [309]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=400)

In [310]:
from sklearn.model_selection import train_test_split
X = df.drop('SalePrice', axis = 1)
X = X.reindex(sorted(X.columns),axis=1)
y = df['SalePrice']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [311]:
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=400)

In [312]:
y_pred = model.predict(X_test)

In [313]:
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test, y_pred))

16367.379863013699

In [314]:
model.fit(X, y)

RandomForestRegressor(n_estimators=400)

In [315]:
result = model.predict(test)

In [316]:
test['SalePrice'] = result
submission = test[['Id','SalePrice']]
submission.to_csv('submission.csv',index=False)